export { default as CImage } from "./image"
export { default as CText } from "./text"
export { default as CButton } from "./button"
export { default as CTextInput } from "./textInput"
export { default as CTitle } from "./title"
export { default as CParagraph } from "./paragraph"
export { default as CDialog } from "./dialog"
export { default as CCaption } from "./caption"
